### ISSUE TITLE
Consider nav behavior more closely.

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kstat-kss-builder#1]
When you open the nav, the content shouldn't shift, just hte nav should open.

**Comment by thiagodemellobueno** [comment]
I disagree.

**Comment by RobLoach** [comment]
Sounds good with me! :wink:

**Comment by thiagodemellobueno** [comment]
well its in there on purpose, but we should debate the whys and hows. 
But lets not be prescriptive. 

I think there are some 'what happens on click'
'how to reopen on navigation etc' that may change any solution to this issue (or possibly non issue) that I think we should discuss once the two big stat projects have shipped ;)

**Comment by andrewmallis** [comment]
back on the table, as per consensus
